#!/bin/bash

PREFIX=$1
EPREFIX=$2
SDKLIBS=$3
SDKINCS=$4
MINIGUI_CROSS_COMPILE=$6
PLAT_DEPENDENT_LIB=${PLATDEPENDENTLIB}
LOCAL_INCS=-I${PREFIX}/include
LOCAL_LIBS=-L${EPREFIX}/lib
FT2_INCS=${LOCAL_INCS}/freetype2
SDK_LIBS=-L${SDKLIBS}
SDK_INCS=-I${SDKINCS}

declare -x CFLAGS=${LOCAL_INCS}" "${SDK_INCS}
declare -x LDFLAGS=${LOCAL_LIBS}" -lz"
declare -x PKG_CONFIG_PATH=${EPREFIX}/lib/pkgconfig
declare -x LIBS=${SDK_LIBS}" "${PLAT_DEPENDENT_LIB}" -lpthread"

./configure    --host=${MINIGUI_CROSS_COMPILE} --prefix=${PREFIX} --exec-prefix=${EPREFIX}
